# Generated by Django 5.1.6 on 2025-07-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_usercourseprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای تخفیف'),
        ),
        migrations.AddField(
            model_name='course',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='قیمت با تخفیف'),
        ),
    ]
