# Generated by Django 5.1.6 on 2025-07-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس کامل'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='زمان\u200cبندی ارسال'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('normal', 'ارسال عادی'), ('express', 'ارسال فوری'), ('digital', 'تحویل دیجیتال')], default='digital', max_length=20, verbose_name='نوع ارسال'),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات سفارش'),
        ),
    ]
