# Generated by Django 5.1.6 on 2025-07-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_address_order_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='تهران', max_length=100, verbose_name='شهر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='el', max_length=100, verbose_name='نام و نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='mobile',
            field=models.CharField(default='0000000000', max_length=15, verbose_name='شماره موبایل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن ثابت'),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='0000000000', max_length=20, verbose_name='کد پستی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.CharField(default='tehran', max_length=100, verbose_name='استان'),
            preserve_default=False,
        ),
    ]
