# Generated by Django 5.1.6 on 2025-07-16 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherRequest',
            new_name='InstructorRequest',
        ),
    ]
