# Generated by Django 5.1.6 on 2025-07-16 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_teacherrequest_instructorrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstructorRequest',
        ),
    ]
