# Generated by Django 5.1.6 on 2025-07-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_instructorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='تایید ایمیل'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_mobile_verified',
            field=models.BooleanField(default=False, verbose_name='تایید موبایل'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='شماره موبایل'),
        ),
    ]
