# Generated by Django 5.1.6 on 2025-07-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_mobileotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'دانشجو'), ('instructor', 'مدرس'), ('admin', 'ادمین')], default='student', max_length=20, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='بیو'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='تأیید ایمیل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_instructor',
            field=models.BooleanField(default=False, verbose_name='مدرس است؟'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_mobile_verified',
            field=models.BooleanField(default=False, verbose_name='تأیید موبایل'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, verbose_name='آی\u200cپی'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='user_agent',
            field=models.CharField(blank=True, max_length=256, verbose_name='مرورگر/دستگاه'),
        ),
    ]
