# Generated by Django 5.1.6 on 2025-07-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='level',
            field=models.CharField(choices=[('beginner', 'مقدماتی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], default='beginner', max_length=12, verbose_name='سطح'),
        ),
    ]
