# Generated by Django 5.1.6 on 2025-07-16 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='instructors/avatars/', verbose_name='عکس پروفایل')),
                ('skills', models.CharField(blank=True, max_length=256, verbose_name='مهارت\u200cها (با کاما جدا کن)')),
                ('linkedin', models.URLField(blank=True, verbose_name='لینک لینکدین')),
                ('website', models.URLField(blank=True, verbose_name='وبسایت شخصی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مدرس',
                'verbose_name_plural': 'مدرسین',
            },
        ),
        migrations.CreateModel(
            name='InstructorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.TextField(verbose_name='انگیزه')),
                ('portfolio_url', models.URLField(blank=True, null=True, verbose_name='نمونه کارها (اختیاری)')),
                ('status', models.CharField(choices=[('pending', 'در حال بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت درخواست')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='توضیح ادمین (در صورت رد شدن)')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_request', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست مدرس شدن',
                'verbose_name_plural': 'درخواست\u200cهای مدرس شدن',
            },
        ),
    ]
