# Generated by Django 5.1.6 on 2025-07-16 22:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorrequest',
            name='admin_note',
        ),
        migrations.RemoveField(
            model_name='instructorrequest',
            name='motivation',
        ),
        migrations.RemoveField(
            model_name='instructorrequest',
            name='portfolio_url',
        ),
        migrations.RemoveField(
            model_name='instructorrequest',
            name='requested_at',
        ),
        migrations.RemoveField(
            model_name='instructorrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='instructorrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructorrequest',
            name='expertise',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructorrequest',
            name='full_name',
            field=models.CharField(default='now', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructorrequest',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instructorrequest',
            name='resume',
            field=models.TextField(default='بدون مقدار'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instructorrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
