# Generated by Django 5.1.6 on 2025-07-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_remove_instructorrequest_admin_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorrequest',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تایید شده؟'),
        ),
        migrations.AddField(
            model_name='instructorrequest',
            name='is_rejected',
            field=models.BooleanField(default=False, verbose_name='رد شده؟'),
        ),
    ]
